/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.js' */
"use strict";

module.exports = {
    plugins: ["@croutonn"],
    rules: {
        "@croutonn/func-style": "error"
    }
};
